### ISSUE TITLE
DynamicCompoundShape

### ISSUE THREAD

**Issue by r00ott** [pmndrs/react-three-jolt#119]
Can you please make a clear documentation about that

**Comment by DennisSmolek** [comment]
> Can you please make a clear documentation about that

It wasn’t in the core at the time I created the shape component.

I might have done some of the functionality ourself but the correct usage will be with the mutableCompoundShape.

It allows the shape to stay the same but with sub shapes changing. 

Hot swapping the shape when subshapes change works as well but is (probably) a little slower.

I’m going to close this as it relates to https://github.com/pmndrs/react-three-jolt/issues/108

but feel free to continue any discussion over there
