### ISSUE TITLE
SourceMaps or something totally off. 

### ISSUE THREAD

**Issue by DennisSmolek** [pmndrs/react-three-jolt#53]
While debugging in the console the names and even line numbers of files are TOTALLY off:
![image](https://github.com/pmndrs/react-three-jolt/assets/1397052/b45e2df7-1fe9-4896-98e4-a50303836457)

I'm not even loading anything related to the Vehicles and they don't have `console.log` there.

**Comment by isaac-mason** [comment]
I can take a look at this

**Comment by isaac-mason** [comment]
Sourcemaps should be working now. Terser (our minifier) was somehow breaking sourcemaps, I've removed it for now.
