### ISSUE TITLE
Consider a @react-three/jolt-addons package

### ISSUE THREAD

**Issue by isaac-mason** [pmndrs/react-three-jolt#67]
`@react-three/rapier` went down the path of having two packages:
- `@react-three/rapier` - which as much as possible just wraps rapier.js
- `@react-three/rapier-addons` - opinionated helpers built using `@react-three/rapier`

I think this is a good split. It keeps the core library light, and makes more sense for those who want to roll their own `Attractor` or `VehicleFourWheel`, character controller, etc.

**Comment by DennisSmolek** [comment]
As discussed in discord I agree.
I think an addons package is fine for unique things like you mentioned but I also think we should have a controllers package that can hold not only the character controller but also the vehicle and camera controllers.

would you mind setting up the packages/npm flows?

I wonder if we can do that with GitHub actions…

**Comment by isaac-mason** [comment]
Created and published `@react-three/jolt-addons` and @react-three/jolt-controllers` now 🙂
